project:
  type: website

website:
  title: "Kyeonghwany Blog"
  
  site-url: 'https://kyeonghwany.github.io'
  site-path: '/'
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts

comments:
  giscus:
    repo: kyeonghwany/kyeonghwany.github.io
    language: ko

format:
  html:

    toc: true
    
    code-fold: false
    code-tools: true
    code-copy: true
    code-line-numbers: false
    code-block-background: true

execute:
  freeze: auto
  cache: true
