project:
  type: website

website:
  title: "Kyeonghwany"
  # site-url: 'https://kyeonghwany.github.io'
  # site-path: '/'
  
  search: true
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
      - href: about.qmd
        text: Portfolio
        
  comments:
    giscus:
      repo: kyeonghwany/kyeonghwany_blog
      language: ko
      
  google-analytics: "G-NDDS4J9T4S"

format:
  html:
    theme:
      - minty
      - custom.scss

    toc: true
    
    code-fold: true
    code-tools: true
    code-copy: true
    code-line-numbers: false
    code-block-background: true