---
title: "portfolio"
---

안녕하세요, 데이터 분석가 김경환입니다. 저는 데이터를 통해 문제를 정의하고 다양한 데이터를 활용하여 문제를 해결하는 것에 관심이 있습니다.

여러 프로젝트 및 사업을 통해 데이터 수집부터 데이터 표준화, 데이터 품질관리, 데이터 분석 및 서비스까지 일련의 과정을 진행한 경험이 있으며 이를 위해 다양한 툴을 활용하여 업무를 진행하고 있습니다.

현재는 의료 마케팅 분야에서 데이터 분석을 하고 있습니다.

## contact

- 📧 james160601\@gmail.com

- [github](https://kyeonghwany.github.io/)


## skills

- R | 데이터 분석

- Python | 데이터 분석, ML/DL

- SQL | 데이터 관리 및 추출

- NIFI | 데이터 수집 및 처리

- DA# | 데이터 관리

- Quarto | 데이터 활용 서비스

## Project list

### 김제 스마트팜 혁신밸리 데이터 수집 및 분석 | 2023.10 - 2024.04

- **(주)좋은정보기술 연구개발팀 근무**
- 혁신밸리 데이터 수집, 처리, 적재 프로세스 구성
- 온실 미기후 데이터 품질관리
- 작물 생육 측정 데이터 품질관리
- 수집 데이터 활용 분석 서비스 제공
- 대시보드 설계

### 전라북도 공공데이터 품질관리 | 2023.09 - 2023.11

- **(주)좋은정보기술 연구개발팀 근무**
- 공공데이터 품질관리 수준평가 대응, 평가 결과 96점 달성
- 업무담당자 대상 공공데이터 품질관리 교육
- 24개 평가 대상 DB 품질진단 및 개선(표준, 구조, 연계, 값 진단 및 개선)
- 개방데이터 품질 진단 및 개선
- [프로젝트 상세](https://kyeonghwany.github.io/project/2024-04-16-opendata-qc.html)

### 고품질 농업 데이터 수집 및 분석 | 2023.06 - 2023.12

- **(주)좋은정보기술 연구개발팀 근무**
- 온실 미기후 데이터 품질관리
- 작물 생육 측정 데이터 품질관리
- 수집 데이터 활용 분석(미기후 데이터 시계열 군집분석, 결측치 처리 모델)

### 차량 이미지 정보 인식 개발 | 2022.07

-   **쏘카 실전 데이터로 배우는 AI 엔지니어 육성 부트캠프 2기**
-   Python, Pytorch
-   차량 이미지에서 차량 부품별 인식
-   차량 사진을 찍은 각도 추출 모델 개발
-   [프로젝트 상세](https://drive.google.com/file/d/1CXLpfBfJhPYrBMrjOHVmabXRp89nWutW/view?usp=share_link)

### 우편서비스 배달업무환경 분석 | 2021.09 - 2022.02

-   **한국전자통신연구원 우정물류기술연구센터 인턴**
-   배달업무 평준화 및 운영 효율화 설계를 위한 배달업무환경 분석
-   초과근무시간 예측을 위한 EDA 및 feature engineering
-   초과근무시간 예측 모델링
-   [프로젝트 상세](https://drive.google.com/file/d/15GbolhdYloIrFsUJy0-skFzFJBMCbSAt/view?usp=share_link)

### 수출동향파악을 위한 수출물량 시계열 분석 | 2021.09 - 2022.02

-   **한국전자통신연구원 우정물류기술연구센터 인턴**
-   공공데이터 API를 이용한 수출물량 자동 수집기 개발
-   주식시장 데이터, 경제지수 데이터 수집
-   국가별 주요 수출 품목 시계열 분석
-   [프로젝트 상세](https://drive.google.com/file/d/1urQF1zCTP3lLPFPViN8HKqlBHrSf_meq/view?usp=share_link)

### 작업복 세탁소 수요 예측 및 입지 분석 | 2021.07 - 2021.08

-   **공공빅데이터 청년 인턴십**
-   공장 위치정보 및 특성, 작업복 세탁량 데이터 전처리
-   작업복 세탁소가 필요한 공장의 특성 도출
-   공장별 작업복 세탁 수요 예측
-   작업복 세탁소 최적 입지 시각화
-   [프로젝트 상세](https://drive.google.com/file/d/1ZcOIvbB3nTSGDUfuXujgmcV7CYm0YnOd/view?usp=share_link)
